export const decisionateLanguageStorageKey =
  "decisionate:language"
export const decisionateLanguageChangedEvent =
  "decisionate:language-changed"

export type DecisionateLanguage =
  | "en"
  | "fr"

export type DecisionateLanguageChange = {
  language: DecisionateLanguage
}

const languageLocales: Record<
  DecisionateLanguage,
  string
> = {
  en: "en-CA",
  fr: "fr-CA",
}

const translations = {
  en: {
    switchToEnglish: "Switch to English",
    switchToFrench: "Passer au français",
    workspace: "Workspace",
    dashboard: "Dashboard",
    dashboards: "Dashboards",
    decisions: "Decisions",
    actionNeeded: "Action Needed",
    workspaceAccess: "Workspace Access",
    analysis: "Analysis",
    insights: "Insights",
    forecasts: "Forecasts",
    reports: "Reports",
    alerts: "Alerts",
    relationships: "Relationships",
    data: "Data",
    datasets: "Datasets",
    entityMatching: "Entity Matching",
    connections: "Connections",
    manage: "Manage",
    settings: "Settings",
    billing: "Billing",
    support: "Support",
    helpSupport: "Help & Support",
    account: "Account",
    businessWorkspace: "Business workspace",
    portal: "portal",
    dashboardNavigation: "Dashboard navigation",
    closeNavigation: "Close dashboard navigation",
    openNavigation: "Open dashboard navigation",
    closeNavigationShort: "Close navigation",
    openNavigationShort: "Open navigation",
    reload: "Reload",
    dismiss: "Dismiss",
  },
  fr: {
    switchToEnglish: "Passer à l'anglais",
    switchToFrench: "Passer au français",
    workspace: "Espace de travail",
    dashboard: "Tableau de bord",
    dashboards: "Tableaux de bord",
    decisions: "Décisions",
    actionNeeded: "Action requise",
    workspaceAccess: "Accès à l'espace de travail",
    analysis: "Analyse",
    insights: "Analyses",
    forecasts: "Prévisions",
    reports: "Rapports",
    alerts: "Alertes",
    relationships: "Relations",
    data: "Données",
    datasets: "Jeux de données",
    entityMatching: "Appariement d'entités",
    connections: "Connexions",
    manage: "Gestion",
    settings: "Paramètres",
    billing: "Facturation",
    support: "Assistance",
    helpSupport: "Aide et assistance",
    account: "Compte",
    businessWorkspace: "Espace de travail professionnel",
    portal: "portail",
    dashboardNavigation: "Navigation du tableau de bord",
    closeNavigation: "Fermer la navigation du tableau de bord",
    openNavigation: "Ouvrir la navigation du tableau de bord",
    closeNavigationShort: "Fermer la navigation",
    openNavigationShort: "Ouvrir la navigation",
    reload: "Recharger",
    dismiss: "Fermer",
  },
} as const

const frenchLandingTranslations: Record<string, string> = {
  "Decisions from Data.": "Des décisions fondées sur les données.",
  "Decisionate home": "Accueil de Decisionate",
  Product: "Produit",
  Solutions: "Solutions",
  "Industry Dashboards": "Tableaux de bord sectoriels",
  Pricing: "Tarifs",
  Resources: "Ressources",
  Company: "Entreprise",
  "Main navigation": "Navigation principale",
  "Mobile navigation": "Navigation mobile",
  "Open Live Demo": "Ouvrir la démo en direct",
  "Close navigation": "Fermer la navigation",
  "Open navigation": "Ouvrir la navigation",
  "Decision intelligence for growing businesses & agencies":
    "L'intelligence décisionnelle pour les entreprises et agences en croissance",
  "Turn your business data into better decisions.":
    "Transformez vos données d'entreprise en meilleures décisions.",
  "Decisionate is a decision intelligence platform powered by your business data. Connect your data, generate AI-powered insights and recommendations, make better decisions and measure outcomes.":
    "Decisionate est une plateforme d'intelligence décisionnelle alimentée par vos données d'entreprise. Connectez vos données, générez des analyses et recommandations assistées par l'IA, prenez de meilleures décisions et mesurez les résultats.",
  "Business intelligence dashboards give your team a clear view of performance before the next decision.":
    "Les tableaux de bord de veille stratégique donnent à votre équipe une vue claire de la performance avant la prochaine décision.",
  "Open the Decisionate product walkthrough":
    "Ouvrir la présentation du produit Decisionate",
  "Watch Demo": "Voir la démo",
  "Start with your existing data": "Commencez avec vos données existantes",
  "Built for growing teams": "Conçu pour les équipes en croissance",
  "Product demo": "Démo du produit",
  "From signal to learning": "Du signal à l'apprentissage",
  "Close product demo": "Fermer la démo du produit",
  "Built for growing businesses, agencies and agency client teams":
    "Conçu pour les entreprises, agences et équipes clientes d'agences en croissance",
  "Owner-led teams": "Équipes dirigées par leurs propriétaires",
  "Agency workspaces": "Espaces de travail d'agence",
  "Client portals": "Portails clients",
  "Evidence-led decisions": "Décisions fondées sur les données probantes",
  "The product workflow": "Le flux de travail du produit",
  "The path from business data to better judgment":
    "Le chemin des données d'entreprise vers un meilleur jugement",
  "Decisionate follows the same order your team does: understand the situation, choose an action, see what happened and carry the lesson forward.":
    "Decisionate suit le même ordre que votre équipe : comprendre la situation, choisir une action, voir ce qui s'est passé et faire progresser l'apprentissage.",
  "Data inputs": "Données d'entrée",
  Evidence: "Données probantes",
  Action: "Action",
  Learning: "Apprentissage",
  "Industry dashboards": "Tableaux de bord sectoriels",
  "Start with a view that understands your business":
    "Commencez avec une vue qui comprend votre entreprise",
  "Use a general view or choose an industry dashboard with measures, comparisons and decision questions shaped for the work you do.":
    "Utilisez une vue générale ou choisissez un tableau de bord sectoriel avec des mesures, comparaisons et questions décisionnelles adaptées à votre activité.",
  "Open live demo": "Ouvrir la démo en direct",
  dashboard: "tableau de bord",
  "Core capabilities": "Capacités essentielles",
  "Everything needed to move from signal to action":
    "Tout ce qu'il faut pour passer du signal à l'action",
  "Use the parts you need today, then connect them into a repeatable decision practice as your business grows.":
    "Utilisez les éléments dont vous avez besoin aujourd'hui, puis reliez-les dans une pratique décisionnelle reproductible à mesure que votre entreprise grandit.",
  "Connect Your Data": "Connectez vos données",
  "Start with the files and systems your business already uses.":
    "Commencez avec les fichiers et systèmes que votre entreprise utilise déjà.",
  "Business Intelligence Dashboards": "Tableaux de bord de veille stratégique",
  "Track KPIs, compare periods and explore business performance in clear, practical dashboards.":
    "Suivez les indicateurs clés, comparez les périodes et explorez la performance de l'entreprise dans des tableaux de bord clairs et pratiques.",
  "Decision Intelligence": "Intelligence décisionnelle",
  "Move from meaningful signals to evidence-backed recommendations and accountable choices.":
    "Passez de signaux pertinents à des recommandations fondées sur les données probantes et à des choix imputables.",
  Forecasting: "Prévisions",
  "Use trends and projections to prepare before a result becomes a surprise.":
    "Utilisez les tendances et projections pour vous préparer avant qu'un résultat ne devienne une surprise.",
  "AI Recommendations": "Recommandations IA",
  "Get an evidence-based next step with context you can review.":
    "Obtenez une prochaine étape fondée sur les données probantes, avec un contexte que vous pouvez examiner.",
  "Decision Tracking": "Suivi des décisions",
  "Give every important choice an owner, outcome and review point.":
    "Donnez à chaque choix important un responsable, un résultat attendu et un point de révision.",
  "Outcome Measurement": "Mesure des résultats",
  "Turn what happened into organizational knowledge for the next decision.":
    "Transformez ce qui s'est passé en connaissances organisationnelles pour la prochaine décision.",
  "The AI decision engine": "Le moteur de décision IA",
  "Charts are the beginning, not the destination.":
    "Les graphiques sont le début, pas la destination.",
  "Decisionate helps teams move from a business signal to a recommendation, then keeps the outcome and lesson attached to the original decision.":
    "Decisionate aide les équipes à passer d'un signal d'entreprise à une recommandation, puis rattache le résultat et l'apprentissage à la décision d'origine.",
  "Human judgment, strengthened by evidence":
    "Le jugement humain, renforcé par les données probantes",
  "Business data": "Données d'entreprise",
  "AI analysis": "Analyse IA",
  Recommendation: "Recommandation",
  Decision: "Décision",
  "Decision lifecycle": "Cycle de vie d'une décision",
  "Keep the decision connected to the result":
    "Gardez la décision liée au résultat",
  "Traditional BI tools often stop at the chart. Decisionate continues through the action, review, outcome and lesson learned.":
    "Les outils de veille stratégique traditionnels s'arrêtent souvent au graphique. Decisionate poursuit avec l'action, la révision, le résultat et l'apprentissage.",
  "A signal worth considering": "Un signal qui mérite attention",
  "A choice with an owner": "Un choix avec un responsable",
  "The work that makes it real": "Le travail qui le rend concret",
  "A moment to look again": "Un moment pour réexaminer",
  Outcome: "Résultat",
  "What actually happened": "Ce qui s'est réellement passé",
  "Lesson learned": "Apprentissage retenu",
  "What to repeat or avoid": "Ce qu'il faut répéter ou éviter",
  Integrations: "Intégrations",
  "Start with the data you already have":
    "Commencez avec les données que vous avez déjà",
  "Connect quickly with available sources today, then expand into the systems your operating model depends on.":
    "Connectez-vous rapidement aux sources disponibles aujourd'hui, puis élargissez vers les systèmes dont dépend votre modèle opérationnel.",
  Available: "Disponible",
  Upcoming: "À venir",
  "Why Decisionate": "Pourquoi Decisionate",
  "A better operating habit, not another reporting tab":
    "Une meilleure habitude de gestion, pas un autre onglet de rapports",
  "Give growing teams a shared way to turn business evidence into action and organizational learning.":
    "Donnez aux équipes en croissance une méthode commune pour transformer les données probantes en action et en apprentissage organisationnel.",
  "Save time": "Gagnez du temps",
  "Move from raw data to a useful next step without rebuilding analysis every week.":
    "Passez des données brutes à une prochaine étape utile sans refaire l'analyse chaque semaine.",
  "Reduce risk": "Réduisez les risques",
  "Make assumptions, ownership, expected outcomes and review dates visible.":
    "Rendez visibles les hypothèses, les responsabilités, les résultats attendus et les dates de révision.",
  "Improve decisions": "Améliorez les décisions",
  "Give teams a shared evidence trail for the choices that matter most.":
    "Donnez aux équipes une piste commune de données probantes pour les choix les plus importants.",
  "Increase revenue": "Augmentez les revenus",
  "Find the commercial signals that deserve action before the window closes.":
    "Trouvez les signaux commerciaux qui méritent une action avant que l'occasion ne se referme.",
  "Track results": "Suivez les résultats",
  "Compare what you expected with what actually happened after the decision.":
    "Comparez ce que vous attendiez à ce qui s'est réellement passé après la décision.",
  "Build knowledge": "Développez les connaissances",
  "Preserve lessons so the organization gets wiser, not just busier.":
    "Conservez les apprentissages pour que l'organisation devienne plus avisée, pas seulement plus occupée.",
  "Plans for businesses and agencies": "Plans pour entreprises et agences",
  "Choose the way you manage decisions": "Choisissez votre mode de gestion des décisions",
  "Start with full access for 30 days. Choose Professional for one business workspace, or scale with agency plans based on client workspaces rather than employee seats.":
    "Commencez avec un accès complet pendant 30 jours. Choisissez Professionnel pour un espace de travail d'entreprise, ou évoluez avec des plans d'agence basés sur les espaces clients plutôt que sur les sièges employés.",
  "CAD / month": "CAD / mois",
  "$0 CAD/year": "$0 CAD/an",
  "$790 CAD/year": "$790 CAD/an",
  "$1,990 CAD/year": "$1 990 CAD/an",
  "Annual billing": "Facturation annuelle",
  "Most popular": "Le plus populaire",
  "Explore Live Demo": "Explorer la démo en direct",
  "1 workspace": "1 espace de travail",
  "1,000 AI credits/month; annual allocation: N/A": "1 000 crédits IA/mois ; allocation annuelle : sans objet",
  "Full access for 30 days": "Accès complet pendant 30 jours",
  "1 workspace during the trial": "1 espace de travail pendant l'essai",
  "Unlimited datasets": "Jeux de données illimités",
  "All industry dashboards": "Tous les tableaux de bord sectoriels",
  "AI-powered recommendations": "Recommandations alimentées par l'IA",
  "Decision management": "Gestion des décisions",
  "Outcome tracking": "Suivi des résultats",
  "White-label client portal": "Portail client en marque blanche",
  "Agency branding": "Image de marque de l'agence",
  "10 client workspaces during the trial": "10 espaces clients pendant l'essai",
  "Need more capacity? Add client workspaces for $20 CAD/month each or $200 CAD/year each. Each additional client workspace includes 2,500 AI credits/month or 30,000/year.":
    "Besoin de plus de capacité ? Ajoutez des espaces clients pour 20 CAD/mois ou 200 CAD/an chacun. Chaque espace client supplémentaire comprend 2 500 crédits IA/mois ou 30 000/an.",
  "Additional AI credit packs are available when your usage grows.":
    "Des forfaits de crédits IA supplémentaires sont disponibles lorsque votre utilisation augmente.",
  "Decisionate pricing and AI credit allocation": "Tarifs Decisionate et allocation de crédits IA",
  "Price (CAD)": "Prix (CAD)",
  "Annual (CAD)": "Annuel (CAD)",
  "Client workspaces": "Espaces clients",
  "AI credits (monthly / annual)": "Crédits IA (mensuels / annuels)",
  "Additional client workspace": "Espace client supplémentaire",
  Questions: "Questions",
  "Frequently asked": "Questions fréquentes",
  "A few useful answers before you start.": "Quelques réponses utiles avant de commencer.",
  "Open the live demo": "Ouvrir la démo en direct",
  "Ready to make better decisions?": "Prêt à prendre de meilleures décisions ?",
  "Start with your data, create your first decision and build the habit of learning from what happens next.":
    "Commencez avec vos données, créez votre première décision et développez l'habitude d'apprendre de ce qui se passe ensuite.",
  "Workflow": "Flux de travail",
  "Live demo": "Démo en direct",
  Support: "Assistance",
  Security: "Sécurité",
  Privacy: "Confidentialité",
  Terms: "Conditions",
  "Decision intelligence for teams that want to act on evidence and learn from the choices they make.":
    "L'intelligence décisionnelle pour les équipes qui veulent agir sur les données probantes et apprendre de leurs choix.",
  "Built for clearer decisions and accountable follow-through.":
    "Conçu pour des décisions plus claires et un suivi imputable.",
  "All rights reserved.": "Tous droits réservés.",
  Decisionate: "Decisionate",
  Dashboard: "Tableau de bord",
  "Live decision signal": "Signal décisionnel en direct",
  "Decision intelligence": "Intelligence décisionnelle",
  "General Business Overview": "Vue d'ensemble générale",
  "Evidence for your next operating decision.":
    "Des données probantes pour votre prochaine décision opérationnelle.",
  Show: "Afficher",
  business: "entreprise",
  marketing: "marketing",
  preview: "aperçu",
  Revenue: "Revenus",
  Decisions: "Décisions",
  "outcomes captured": "résultats enregistrés",
  "+6 this month": "+6 ce mois-ci",
  "Revenue trend": "Tendance des revenus",
  "Monthly performance": "Performance mensuelle",
  "AI recommendation": "Recommandation IA",
  "Protect the improving trend with a focused next action.":
    "Protégez la tendance à la hausse avec une action ciblée.",
  "Based on trend, target progress and prior outcomes.":
    "Fondé sur la tendance, la progression de la cible et les résultats précédents.",
  "Review recommendation": "Examiner la recommandation",
  "3 decisions need an outcome review": "3 décisions nécessitent une révision du résultat",
  "Decision queue": "File des décisions",
  "Outcome tracking included": "Suivi des résultats inclus",
  Connect: "Connecter",
  Analyze: "Analyser",
  Forecast: "Prévision",
  Recommend: "Recommander",
  Decide: "Décider",
  "Bring in files, analytics, accounting, commerce, marketing, or database data.":
    "Importez des fichiers et des données d'analyse, de comptabilité, de commerce, de marketing ou de bases de données.",
  "Use business intelligence dashboards to see the measures, patterns and changes that matter.":
    "Utilisez des tableaux de bord de veille stratégique pour voir les mesures, tendances et changements importants.",
  "Understand what current signals may mean next.":
    "Comprenez ce que les signaux actuels pourraient annoncer.",
  "Turn evidence into a clear next action.":
    "Transformez les données probantes en prochaine action claire.",
  "Record the choice, owner, expected result and review date.":
    "Enregistrez le choix, le responsable, le résultat attendu et la date de révision.",
  "Capture outcomes and lessons for better future decisions.":
    "Enregistrez les résultats et les apprentissages pour de meilleures décisions futures.",
  "CSV / Excel / Systems": "CSV / Excel / Systèmes",
  "Analytics engine": "Moteur analytique",
  Recommendations: "Recommandations",
  "Decisions / Outcomes / Lessons": "Décisions / Résultats / Apprentissages",
  "Open the live demo for the": "Ouvrir la démo en direct du",
  "General Business": "Entreprise générale",
  "A practical view of growth, efficiency and operating health.":
    "Une vue pratique de la croissance, de l'efficacité et de la santé opérationnelle.",
  Marketing: "Marketing",
  "Connect campaign performance to pipeline and revenue decisions.":
    "Reliez la performance des campagnes aux décisions concernant le pipeline et les revenus.",
  Sales: "Ventes",
  "Track funnel movement, conversion and the decisions behind results.":
    "Suivez l'évolution de l'entonnoir, la conversion et les décisions derrière les résultats.",
  Retail: "Commerce de détail",
  "Find the product, channel and period signals shaping demand.":
    "Trouvez les signaux de produit, de canal et de période qui façonnent la demande.",
  Restaurant: "Restaurant",
  "Make clearer decisions about covers, sales, labor and margins.":
    "Prenez de meilleures décisions concernant les couverts, les ventes, la main-d'oeuvre et les marges.",
  "Hotels & Hospitality": "Hôtels et hôtellerie",
  "Connect occupancy, room revenue, booking channels and guest experience.":
    "Reliez l'occupation, les revenus des chambres, les canaux de réservation et l'expérience client.",
  "Professional Services": "Services professionnels",
  "Connect utilization, delivery, clients and commercial performance.":
    "Reliez l'utilisation, la prestation, les clients et la performance commerciale.",
  Healthcare: "Soins de santé",
  "Bring service demand, capacity, quality and follow-up into view.":
    "Mettez en évidence la demande de services, la capacité, la qualité et le suivi.",
  Construction: "Construction",
  "Connect project progress, costs, resources and delivery decisions.":
    "Reliez l'avancement des projets, les coûts, les ressources et les décisions de livraison.",
  "Law Firm": "Cabinet d'avocats",
  "Understand matter workload, realization, clients and team capacity.":
    "Comprenez la charge des dossiers, la réalisation, les clients et la capacité de l'équipe.",
  "Auto Repair Shop": "Atelier de réparation automobile",
  "Track repair orders, service mix, bay utilization and return visits.":
    "Suivez les ordres de réparation, le mix de services, l'utilisation des baies et les visites de retour.",
  "Sage Cloud Accounting": "Comptabilité Sage Cloud",
  "Zoho Books": "Zoho Books",
  "Learn": "Apprendre",
  Free: "Gratuit",
  Professional: "Professionnel",
  Agency: "Agence",
  "Decision intelligence for a business managing its own workspace.":
    "L'intelligence décisionnelle pour une entreprise qui gère son propre espace de travail.",
  "Manage an agency workspace and up to 10 client workspaces.":
    "Gérez un espace de travail d'agence et jusqu'à 10 espaces clients.",
  "5,000 AI credits/month or 60,000/year": "5 000 crédits IA/mois ou 60 000/an",
  "25,000 AI credits/month or 300,000/year": "25 000 crédits IA/mois ou 300 000/an",
  "What is Decisionate?": "Qu'est-ce que Decisionate ?",
  "How does decision intelligence work?": "Comment fonctionne l'intelligence décisionnelle ?",
  "Can I upload files?": "Puis-je téléverser des fichiers ?",
  "Which connectors are available?": "Quels connecteurs sont disponibles ?",
  "What can I do with the dashboards?": "Que puis-je faire avec les tableaux de bord ?",
  "Can I combine data from more than one dataset?": "Puis-je combiner des données de plusieurs jeux de données ?",
  "How do AI recommendations and forecasts work?": "Comment fonctionnent les recommandations et prévisions IA ?",
  "What are alerts used for?": "À quoi servent les alertes ?",
  "How does Decisionate learn from decisions?": "Comment Decisionate apprend-il des décisions ?",
  "Can I export decisions?": "Puis-je exporter les décisions ?",
  "How are workspaces and permissions organized?": "Comment les espaces de travail et les permissions sont-ils organisés ?",
  "Can an agency manage client workspaces?": "Une agence peut-elle gérer des espaces clients ?",
  "Is there a live demo?": "Existe-t-il une démo en direct ?",
  "What does the free trial include?": "Que comprend l'essai gratuit ?",
  "What are Decisionate AI credits?": "Que sont les crédits IA Decisionate ?",
  "Is my data secure?": "Mes données sont-elles sécurisées ?",
  "Decisionate is a decision intelligence platform for growing businesses and agencies. It connects business data to analysis, forecasts, recommendations, accountable decisions and outcome learning.":
    "Decisionate est une plateforme d'intelligence décisionnelle pour les entreprises et agences en croissance. Elle relie les données d'entreprise à l'analyse, aux prévisions, aux recommandations, aux décisions imputables et à l'apprentissage des résultats.",
  "Yes. CSV, Excel, JSON and Parquet files can be uploaded. The dataset schema comes from the incoming file, and you can choose the date, dimension and metric columns used for analysis.":
    "Oui. Les fichiers CSV, Excel, JSON et Parquet peuvent être téléversés. Le schéma du jeu de données provient du fichier entrant, et vous pouvez choisir les colonnes de date, de dimension et de métrique utilisées pour l'analyse.",
  "Yes. The live demo can be opened without signing in and uses prepared demonstration datasets. It is read-only: demo data cannot be uploaded or deleted, and creating decisions is disabled.":
    "Oui. La démo en direct peut être ouverte sans connexion et utilise des jeux de données préparés. Elle est en lecture seule : les données de démo ne peuvent pas être téléversées ou supprimées et la création de décisions est désactivée.",
  "How can I get help?": "Comment puis-je obtenir de l'aide ?",
  "Use Help & Support inside the application to contact support through the web form, report a bug, request a feature or review the product reference guide. Workspace, account, page and session context are attached automatically to support requests.":
    "Utilisez Aide et assistance dans l'application pour contacter le support via le formulaire, signaler un bogue, demander une fonctionnalité ou consulter le guide de référence. Le contexte de l'espace, du compte, de la page et de la session est joint automatiquement aux demandes.",
  "Pause demo": "Mettre la démo en pause",
  "Play demo": "Lire la démo",
  "Decisionate workflow": "Flux de travail Decisionate",
  step: "étape",
  Step: "Étape",
  of: "sur",
  "Do this": "À faire",
  "Get this": "Vous obtenez",
  "Connected sources": "Sources connectées",
  "Metric mapping": "Mappage des métriques",
  "Relationship analysis": "Analyse des relations",
  "Alert monitor": "Surveillance des alertes",
  "New decision": "Nouvelle décision",
  "Outcome review": "Révision du résultat",
  "Forecast evidence": "Données probantes de prévision",
  "Business performance": "Performance de l'entreprise",
  "Ready for analysis": "Prêt pour l'analyse",
  "Use the columns that answer the question": "Utilisez les colonnes qui répondent à la question",
  "Observed association, not proven causation": "Association observée, sans causalité prouvée",
  "Signals checked against recent patterns": "Signaux comparés aux tendances récentes",
  "Recommendation converted to action": "Recommandation convertie en action",
  "Evidence returned to the decision loop": "Données probantes réintégrées dans la boucle de décision",
  "Historical actuals compared with the forecast": "Résultats historiques comparés aux prévisions",
  "Last 7 periods": "7 dernières périodes",
  Actual: "Réel",
  Analytics: "Analytique",
  CRM: "CRM",
  Mapped: "Mappé",
  Connected: "Connecté",
  Detected: "Détecté",
  "Monthly sum": "Somme mensuelle",
  "Meta Ads · Ad spend": "Meta Ads · Dépenses publicitaires",
  Input: "Entrée",
  "Revenue · Monthly sum": "Revenus · Somme mensuelle",
  "about 1 month": "environ 1 mois",
  "Unusual increase detected": "Hausse inhabituelle détectée",
  "24% above range": "24 % au-dessus de la plage",
  Expected: "Attendu",
  "Repeat the tested offer with the strongest channel mix.":
    "Répétez l'offre testée avec le meilleur mix de canaux.",
  "Alert signal": "Signal d'alerte",
  "Decision record": "Fiche de décision",
  "Learning evidence": "Données probantes d'apprentissage",
  "Relationship context": "Contexte de relation",
  "Dashboard signal": "Signal du tableau de bord",
  "Revenue is outside its recent expected range.": "Les revenus sont hors de leur plage récente attendue.",
  "Increase campaign focus for the next review period.": "Augmentez l'attention portée à la campagne pour la prochaine période de révision.",
  "Outcome recorded. Lesson added to future context.": "Résultat enregistré. Apprentissage ajouté au contexte futur.",
  "Ad spend and revenue move together with a one-month observed delay.": "Les dépenses publicitaires et les revenus évoluent ensemble avec un décalage observé d'un mois.",
  "Revenue is moving above its recent baseline.": "Les revenus dépassent leur référence récente.",
  Example: "Exemple",
  "Start again": "Recommencer",
  "Next step": "Étape suivante",
  "Demo progress": "Progression de la démo",
  "Jump to": "Aller à",
  "Restart demo": "Redémarrer la démo",
  "Revenue is up 18% since the previous period": "Les revenus ont augmenté de 18 % depuis la période précédente",
  "Focus the highest-converting channel": "Concentrez-vous sur le canal qui convertit le mieux",
  "Increase qualified leads by 12%": "Augmentez les prospects qualifiés de 12 %",
  "Review date": "Date de révision",
  "Jul 31, 2026": "31 juill. 2026",
  "Successful · Actual revenue: $12,400 · Lesson: repeat the tested offer": "Réussite · Revenus réels : 12 400 $ · Apprentissage : répéter l'offre testée",
  "Decisionate follows a connected workflow: bring in business data, analyze the signals, review a recommendation, create an owned decision, record the outcome and capture the lesson for future recommendations. Decisions remain accountable to your team; the platform supports the decision rather than taking unapproved action.":
    "Decisionate suit un flux de travail connecté : importez les données d'entreprise, analysez les signaux, examinez une recommandation, créez une décision attribuée, enregistrez le résultat et retenez l'apprentissage pour les recommandations futures. Les décisions restent sous la responsabilité de votre équipe ; la plateforme les accompagne sans prendre d'actions non approuvées.",
  "The current connector set includes Google Analytics, Google Ads, Google Business Profile, Google Search Console, PostgreSQL, MySQL, SQL Server, Stripe, Shopify, QuickBooks, FreshBooks, Xero, HubSpot, Meta Ads and Salesforce Sales Cloud. Salesforce Sales Cloud currently supports Accounts, Leads and Opportunities. Connector credentials and provider setup are managed before a workspace runs its first sync.":
    "Les connecteurs actuels comprennent Google Analytics, Google Ads, Google Business Profile, Google Search Console, PostgreSQL, MySQL, SQL Server, Stripe, Shopify, QuickBooks, FreshBooks, Xero, HubSpot, Meta Ads et Salesforce Sales Cloud. Salesforce Sales Cloud prend actuellement en charge les comptes, prospects et opportunités. Les identifiants et la configuration des fournisseurs sont gérés avant la première synchronisation d'un espace de travail.",
  "Dashboards provide business intelligence views for performance analysis, including general business, decision, sales, marketing and industry-specific views. You can select datasets and metrics, set date periods, aggregate by day, week, month or quarter, use sum, count, average, minimum or maximum, and compare relevant metrics.":
    "Les tableaux de bord offrent des vues de veille stratégique pour analyser la performance, notamment des vues générales, décisionnelles, commerciales, marketing et sectorielles. Vous pouvez sélectionner des jeux de données et des métriques, définir des périodes, agréger par jour, semaine, mois ou trimestre, utiliser la somme, le décompte, la moyenne, le minimum ou le maximum, et comparer les métriques pertinentes.",
  "Yes. Datasets can be joined on normalized time periods, and related metrics can be analyzed together. The resulting data remains scoped to the active workspace and can support dashboard analysis and decisions.":
    "Oui. Les jeux de données peuvent être joints sur des périodes normalisées et les métriques liées peuvent être analysées ensemble. Les données résultantes restent limitées à l'espace de travail actif et peuvent alimenter l'analyse des tableaux de bord et les décisions.",
  "When AI is configured, Decisionate provides recommendations using bounded analytical summaries, selected metrics and relevant historical decision outcomes. Forecasts use the selected time series and aggregation settings. Recommendations and forecasts are evidence to review, not guarantees or proof of causation.":
    "Lorsque l'IA est configurée, Decisionate fournit des recommandations à partir de résumés analytiques encadrés, de métriques sélectionnées et de résultats historiques pertinents. Les prévisions utilisent la série temporelle et les paramètres d'agrégation sélectionnés. Les recommandations et prévisions sont des données probantes à examiner, pas des garanties ni des preuves de causalité.",
  "Workspace owners can configure alerts around selected datasets, metrics and optional KPI targets. Alerts can identify meaningful changes and deliver reports or recommendations by email on the configured schedule. Alert data and recipients are isolated by workspace.":
    "Les propriétaires d'espaces de travail peuvent configurer des alertes autour de jeux de données, métriques et cibles d'indicateurs sélectionnés. Les alertes peuvent détecter des changements importants et envoyer des rapports ou recommandations par courriel selon l'horaire configuré. Les données et destinataires des alertes sont isolés par espace de travail.",
  "Each decision can include an owner, action, expected outcome, review details, actual outcome, status and lesson learned. That history becomes bounded evidence that can inform later recommendations while remaining subject to human review.":
    "Chaque décision peut inclure un responsable, une action, un résultat attendu, des détails de révision, le résultat réel, un statut et un apprentissage. Cet historique devient une donnée probante encadrée pouvant éclairer les recommandations ultérieures, tout en restant soumise à l'examen humain.",
  "The workspace owner can export the current decision results as CSV for analysis or JSON for complete structured records, including ownership, timestamps, outcomes, notes, lessons and activity history. Export activity is logged. Connector source data is not offered as a separate data export.":
    "Le propriétaire de l'espace de travail peut exporter les résultats actuels des décisions en CSV pour l'analyse ou en JSON pour obtenir les enregistrements structurés complets, y compris les responsables, horodatages, résultats, notes, apprentissages et historique d'activité. Les exportations sont journalisées. Les données sources des connecteurs ne sont pas proposées comme export séparé.",
  "Each workspace is isolated. Professional workspaces support an owner and members. Agency workspaces can manage client workspaces, with agency branding and separate client access. Owners control settings, members, connections and other management actions according to the workspace role model.":
    "Chaque espace de travail est isolé. Les espaces Professionnel prennent en charge un propriétaire et des membres. Les espaces d'agence peuvent gérer des espaces clients, avec l'image de marque de l'agence et des accès clients séparés. Les propriétaires contrôlent les paramètres, membres, connexions et autres actions de gestion selon le modèle de rôles de l'espace.",
  "Yes. Agency plans include an agency workspace and client workspaces. Agency owners can create and manage client access, while client users work within their own client workspace and see the access permitted by their role.":
    "Oui. Les plans d'agence comprennent un espace d'agence et des espaces clients. Les propriétaires d'agence peuvent créer et gérer les accès clients, tandis que les utilisateurs clients travaillent dans leur propre espace et voient les accès autorisés par leur rôle.",
  "The 30-day free trial provides the full Professional or Agency feature set, with the plan's included AI credits, and no credit card is required. Professional trials include 1 workspace, while Agency trials include 10 client workspaces. Professional includes 5,000 AI credits/month or 60,000/year and costs $79 CAD/month or $790 CAD/year. Agency includes 25,000 AI credits/month or 300,000/year and costs $199 CAD/month or $1,990 CAD/year. Additional client workspaces are $20 CAD/month or $200 CAD/year each.":
    "L'essai gratuit de 30 jours offre toutes les fonctionnalités Professionnel ou Agence, avec les crédits IA inclus dans le plan, sans carte de crédit. Les essais Professionnel comprennent 1 espace de travail, tandis que les essais Agence comprennent 10 espaces clients. Professionnel comprend 5 000 crédits IA/mois ou 60 000/an et coûte 79 CAD/mois ou 790 CAD/an. Agence comprend 25 000 crédits IA/mois ou 300 000/an et coûte 199 CAD/mois ou 1 990 CAD/an. Les espaces clients supplémentaires coûtent 20 CAD/mois ou 200 CAD/an chacun.",
  "Decisionate AI credits are an application usage allowance, not OpenAI credits or currency. The default monthly allocations are 1,000 for Free, 5,000 for Professional and 25,000 for Agency. Free has no annual allocation; Professional and Agency annual allocations are twelve times their monthly amounts: 60,000 and 300,000. Each additional client workspace includes 2,500 AI credits/month or 30,000/year. Allocations can be adjusted by the platform administrator as usage and provider costs change.":
    "Les crédits IA Decisionate sont une allocation d'utilisation de l'application, et non des crédits OpenAI ou une monnaie. Les allocations mensuelles par défaut sont de 1 000 pour Gratuit, 5 000 pour Professionnel et 25 000 pour Agence. Gratuit n'a pas d'allocation annuelle ; les allocations annuelles de Professionnel et Agence correspondent à douze fois leurs montants mensuels : 60 000 et 300 000. Chaque espace client supplémentaire comprend 2 500 crédits IA/mois ou 30 000/an. Les allocations peuvent être ajustées par l'administrateur de la plateforme selon l'utilisation et les coûts des fournisseurs.",
  "Workspace access is isolated, management actions are role-protected, connector credentials are handled separately from workspace data, and shared dashboards use controlled links. Review the Security, Privacy and Terms pages for the current controls, processors, AI data handling, retention and deletion commitments.":
    "L'accès aux espaces de travail est isolé, les actions de gestion sont protégées par rôle, les identifiants des connecteurs sont traités séparément des données de l'espace et les tableaux de bord partagés utilisent des liens contrôlés. Consultez les pages Sécurité, Confidentialité et Conditions pour connaître les contrôles, sous-traitants, traitements IA, engagements de conservation et de suppression actuels.",
  "Start with one workspace and a practical monthly AI allowance.": "Commencez avec un espace de travail et une allocation mensuelle pratique de crédits IA.",
  "Upload a CSV or Excel file, or connect a source your team already uses.": "Téléversez un fichier CSV ou Excel, ou connectez une source déjà utilisée par votre équipe.",
  "Choose a source and bring a dataset into the workspace.": "Choisissez une source et importez un jeu de données dans l'espace de travail.",
  "A shared, analyzable dataset with its columns and time range ready to inspect.": "Un jeu de données partagé et analysable, avec ses colonnes et sa période prêts à être examinés.",
  "Example: Google Analytics marketing data": "Exemple : données marketing Google Analytics",
  "Tell Decisionate what matters": "Indiquez à Decisionate ce qui compte",
  "Select the dataset, metrics, date range, aggregation and dashboard that frame the question.": "Sélectionnez le jeu de données, les métriques, la période, l'agrégation et le tableau de bord qui cadrent la question.",
  "Map a business metric to a source column and set the analysis period.": "Associez une métrique d'entreprise à une colonne source et définissez la période d'analyse.",
  "Every KPI and chart uses the same metric, period and aggregation choices.": "Chaque indicateur et graphique utilise les mêmes choix de métrique, de période et d'agrégation.",
  "Revenue → revenue · Jan 1–Jun 30 · Monthly sum": "Revenus → revenue · 1 janv.–30 juin · Somme mensuelle",
  "Connect the signals behind a decision": "Reliez les signaux derrière une décision",
  "Relate metrics from separate sources by normalized periods when one dataset does not tell the whole story.": "Reliez les métriques de sources distinctes par périodes normalisées lorsqu'un seul jeu de données ne raconte pas toute l'histoire.",
  "Compare marketing spend with revenue and let Decisionate test sensible timing automatically.": "Comparez les dépenses marketing aux revenus et laissez Decisionate tester automatiquement des décalages pertinents.",
  "A business-friendly association with strength, matched periods and the observed delay.": "Une association compréhensible pour l'entreprise, avec sa force, ses périodes correspondantes et le décalage observé.",
  "Strong association · Revenue follows ad spend by about 1 month": "Association forte · Les revenus suivent les dépenses publicitaires d'environ 1 mois",
  "Keep important changes in view": "Gardez les changements importants en vue",
  "Anomaly detection, targets and scheduled alerts help surface meaningful changes without requiring someone to watch every chart.": "La détection d'anomalies, les cibles et les alertes planifiées font ressortir les changements importants sans obliger quelqu'un à surveiller chaque graphique.",
  "Choose a metric, define an optional target and configure an alert delivery channel.": "Choisissez une métrique, définissez une cible facultative et configurez un canal de diffusion des alertes.",
  "A concise signal with the evidence, recommendation and next step ready for review.": "Un signal concis avec les données probantes, la recommandation et la prochaine étape prêts à être examinés.",
  "Unusual increase · Revenue is 24% above its recent expected range": "Hausse inhabituelle · Les revenus sont 24 % au-dessus de leur plage récente attendue",
  "See the signal behind the numbers": "Voyez le signal derrière les chiffres",
  "Use dashboards, KPIs, comparisons and category breakdowns to understand what changed.": "Utilisez les tableaux de bord, indicateurs, comparaisons et ventilations par catégorie pour comprendre ce qui a changé.",
  "Compare performance and look for a meaningful movement before acting.": "Comparez la performance et cherchez un mouvement significatif avant d'agir.",
  "A focused view of the evidence behind the business question.": "Une vue ciblée des données probantes derrière la question d'entreprise.",
  "Turn evidence into a next action": "Transformez les données probantes en prochaine action",
  "Forecasts and recommendations combine current signals with historical decision learning, with transparent fallback guidance when AI is unavailable.": "Les prévisions et recommandations combinent les signaux actuels à l'apprentissage historique des décisions, avec des indications de repli transparentes lorsque l'IA n'est pas disponible.",
  "Review the forecast, confidence, risks and supporting evidence.": "Examinez la prévision, le niveau de confiance, les risques et les données probantes à l'appui.",
  "A recommendation you can review and convert into a decision with its evidence preserved.": "Une recommandation que vous pouvez examiner et convertir en décision tout en conservant ses données probantes.",
  "Make the choice accountable": "Rendez le choix imputable",
  "Convert a recommendation into a decision with an owner, expected outcome and review date.": "Convertissez une recommandation en décision avec un responsable, un résultat attendu et une date de révision.",
  "Record what will be done, the expected outcome and how success will be measured.": "Enregistrez ce qui sera fait, le résultat attendu et la façon dont le succès sera mesuré.",
  "A decision record that can be reviewed instead of disappearing into a chat or meeting.": "Une fiche de décision qui peut être examinée au lieu de disparaître dans une conversation ou une réunion.",
  "Make the next recommendation wiser": "Rendez la prochaine recommandation plus pertinente",
  "Record the actual result, outcome status and lesson learned when the decision is reviewed.": "Enregistrez le résultat réel, le statut du résultat et l'apprentissage lors de la révision de la décision.",
  "Compare the expected outcome with what happened and capture the lesson.": "Comparez le résultat attendu à ce qui s'est passé et retenez l'apprentissage.",
  "Future recommendations can use your workspace's own decision evidence.": "Les recommandations futures peuvent utiliser les propres données probantes décisionnelles de votre espace.",
  Reports: "Rapports",
  Datasets: "Jeux de données",
  Connections: "Connexions",
  Settings: "Paramètres",
  Billing: "Facturation",
  Alerts: "Alertes",
  "Action Needed": "Action requise",
  "Workspace Access": "Accès à l'espace de travail",
  "Help & Support": "Aide et assistance",
  "Cross-source entity matching": "Appariement d'entités entre sources",
  "Cross-source relationships": "Relations entre sources",
  "Review generated patterns for one dataset or analyze selected metrics across multiple datasets.": "Examinez les tendances générées pour un jeu de données ou analysez des métriques sélectionnées dans plusieurs jeux de données.",
  "Forecast future trends from your datasets so decision reviews can include a clear outlook and confidence signal.": "Prévoyez les tendances futures à partir de vos jeux de données afin que les révisions de décisions incluent une perspective claire et un signal de confiance.",
  "Select the data and relationships that should shape alert analysis.": "Sélectionnez les données et relations qui doivent orienter l'analyse des alertes.",
  "Configure periodic KPI email messages and AI-assisted recommendations for workspace owners, teammates, or client recipients.": "Configurez des courriels périodiques sur les indicateurs et des recommandations assistées par l'IA pour les propriétaires, coéquipiers ou destinataires clients.",
  "Review external data source connections for this workspace. Configuration and synchronization are managed by the workspace owner.": "Examinez les connexions aux sources de données externes de cet espace. La configuration et la synchronisation sont gérées par le propriétaire de l'espace.",
  "Configure external business systems that can feed datasets, forecasts, reports, alerts, and decisions.": "Configurez les systèmes d'entreprise externes pouvant alimenter les jeux de données, prévisions, rapports, alertes et décisions.",
  "A concise guide to getting value from Decisionate, resolving issues, and turning evidence into better decisions.": "Un guide concis pour tirer de la valeur de Decisionate, résoudre les problèmes et transformer les données probantes en meilleures décisions.",
  "Billing configuration is available to the business owner.": "La configuration de la facturation est disponible pour le propriétaire de l'entreprise.",
  "Review your current plan, trial status, usage, and billing options.": "Examinez votre plan actuel, le statut de votre essai, votre utilisation et vos options de facturation.",
  "Choose the professionally designed dashboard that becomes your main workspace view.": "Choisissez le tableau de bord professionnel qui deviendra la vue principale de votre espace.",
  "Track decisions, review outcomes, and learn what works.": "Suivez les décisions, examinez les résultats et apprenez ce qui fonctionne.",
  "Resolve decisions with pending outcomes, pending learning, or overdue reviews.": "Traitez les décisions dont les résultats ou apprentissages sont en attente ou dont la révision est en retard.",
  "This shared workspace is read-only. The business owner handles dataset uploads, connections, and changes.": "Cet espace partagé est en lecture seule. Le propriétaire de l'entreprise gère les téléversements, connexions et modifications des jeux de données.",
  "This client workspace is read-only. You can review decisions and their activity here.": "Cet espace client est en lecture seule. Vous pouvez y examiner les décisions et leur activité.",
  "Analysis and metric selection are available in this shared workspace. Workspace managers handle decision creation and data changes.": "L'analyse et la sélection des métriques sont disponibles dans cet espace partagé. Les gestionnaires de l'espace créent les décisions et modifient les données.",
  "Notification setup is managed by workspace owners and approved agency owners.": "La configuration des notifications est gérée par les propriétaires d'espaces et les propriétaires d'agence autorisés.",
  "Only workspace owners can run entity matching. You can still review existing analysis in this workspace.": "Seuls les propriétaires d'espaces peuvent lancer l'appariement d'entités. Vous pouvez toutefois examiner l'analyse existante dans cet espace.",
  "Select 2 to 10 datasets, confirm the identity columns used for matching, and choose the metrics or columns to carry into the unified dataset. Recommended columns are selected automatically and can be changed.": "Sélectionnez de 2 à 10 jeux de données, confirmez les colonnes d'identité utilisées pour l'appariement et choisissez les métriques ou colonnes à intégrer au jeu unifié. Les colonnes recommandées sont sélectionnées automatiquement et peuvent être modifiées.",
  "Choose two datasets and confirm how their metrics relate over shared periods.": "Choisissez deux jeux de données et confirmez comment leurs métriques sont liées sur des périodes communes.",
  "Saved definitions are recalculated from the latest dataset contents when opened.": "Les définitions enregistrées sont recalculées à partir du contenu le plus récent des jeux de données à leur ouverture.",
  "No cross-source relationships saved yet.": "Aucune relation entre sources n'est encore enregistrée.",
  "This is a read-only workspace. Open a decision to review its follow-up details; workspace managers handle updates.": "Cet espace est en lecture seule. Ouvrez une décision pour examiner son suivi ; les gestionnaires de l'espace effectuent les mises à jour.",
  "Select a dataset": "Sélectionner un jeu de données",
  "Select a metric": "Sélectionner une métrique",
  "Select dataset": "Sélectionner un jeu de données",
  "Select metric": "Sélectionner une métrique",
  "Metrics unavailable": "Métriques indisponibles",
  "Upload a supported CSV, Excel, JSON, or Parquet file on": "Téléversez un fichier CSV, Excel, JSON ou Parquet pris en charge dans",
  "to start building dashboards, forecasts, reports, and decisions.": "pour commencer à créer des tableaux de bord, prévisions, rapports et décisions.",
  "Sign in to load datasets.": "Connectez-vous pour charger les jeux de données.",
  "Failed to load datasets": "Impossible de charger les jeux de données",
  "None": "Aucun",
  "Try again": "Réessayer",
  "Dashboard home": "Accueil du tableau de bord",
  "Dashboard unavailable": "Tableau de bord indisponible",
  "Something went wrong while loading this dashboard. Try again, or return to the dashboard home.": "Un problème est survenu lors du chargement de ce tableau de bord. Réessayez ou retournez à l'accueil du tableau de bord.",
  "Shared dashboard unavailable": "Tableau de bord partagé indisponible",
  "Something went wrong while loading this shared dashboard. Try again or return to the Decisionate home page.": "Un problème est survenu lors du chargement de ce tableau de bord partagé. Réessayez ou retournez à l'accueil de Decisionate.",
  Reference: "Référence",
  "Loading...": "Chargement...",
  "Loading dashboard...": "Chargement du tableau de bord...",
  "Updating AI analysis for the selected metric...": "Mise à jour de l'analyse IA pour la métrique sélectionnée...",
  "AI analysis is unavailable for the selected metric. The other dashboard data is still available.": "L'analyse IA n'est pas disponible pour la métrique sélectionnée. Les autres données du tableau de bord restent disponibles.",
  "Retry AI analysis": "Réessayer l'analyse IA",
  "Recommended Action": "Action recommandée",
  confidence: "confiance",
  high: "élevée",
  low: "faible",
  "Why:": "Pourquoi :",
  "Analysis basis:": "Base de l'analyse :",
  "Creating...": "Création...",
  "Create Decision": "Créer une décision",
  "Before you create your account": "Avant de créer votre compte",
  "Please review and accept both documents to continue to sign up.": "Veuillez consulter et accepter les deux documents pour continuer l'inscription.",
  "I have read and agree to the": "J'ai lu et j'accepte les",
  "Terms of Service": "Conditions d'utilisation",
  "I have read and acknowledge the": "J'ai lu et je reconnais la",
  "Privacy Policy": "Politique de confidentialité",
  "You can continue after both acknowledgements are selected.": "Vous pourrez continuer après avoir sélectionné les deux confirmations.",
  "Terms of Service and Privacy Policy acknowledged.": "Les Conditions d'utilisation et la Politique de confidentialité ont été reconnues.",
  "Loading sign in...": "Chargement de la connexion...",
  "Loading sign up...": "Chargement de l'inscription...",
  "Sign-in service could not be loaded.": "Le service de connexion n'a pas pu être chargé.",
  "Check the connection and try again.": "Vérifiez la connexion et réessayez.",
  "Create your Decisionate workspace": "Créer votre espace de travail Decisionate",
  "Sign in": "Se connecter",
  "Sign up": "S'inscrire",
  "Workspace setup": "Configuration de l'espace de travail",
  "Welcome to Decisionate": "Bienvenue dans Decisionate",
  "Create the workspace that will hold your datasets, dashboards, reports, alerts, and decisions. You can use it for your own business or for agency-managed client work.": "Créez l'espace qui contiendra vos jeux de données, tableaux de bord, rapports, alertes et décisions. Vous pouvez l'utiliser pour votre entreprise ou pour le travail client géré par une agence.",
  "Opening your workspace...": "Ouverture de votre espace de travail...",
  "Checking existing workspace...": "Vérification de l'espace de travail existant...",
  "Your details": "Vos informations",
  "First name": "Prénom",
  "Last name": "Nom",
  "Work email:": "Courriel professionnel :",
  "Not available": "Non disponible",
  "Create your workspace": "Créez votre espace de travail",
  "Company or agency name": "Nom de l'entreprise ou de l'agence",
  "Workspace type": "Type d'espace de travail",
  Country: "Pays",
  "Select a country": "Sélectionnez un pays",
  Continue: "Continuer",
  "Personalize Decisionate": "Personnalisez Decisionate",
  Industry: "Secteur",
  "Select an industry": "Sélectionnez un secteur",
  "Company size": "Taille de l'entreprise",
  "Select company size": "Sélectionnez la taille de l'entreprise",
  "Clients currently managed": "Clients actuellement gérés",
  "Select client count": "Sélectionnez le nombre de clients",
  "Role or job function": "Rôle ou fonction",
  "Select your role": "Sélectionnez votre rôle",
  "Primary goal with Decisionate": "Objectif principal avec Decisionate",
  "Select your primary goal": "Sélectionnez votre objectif principal",
  "Your Agency trial includes full plan access for one month. No credit card is required.": "Votre essai Agence comprend un accès complet au plan pendant un mois. Aucune carte de crédit n'est requise.",
  "Your Professional trial includes full plan access for one month. No credit card is required.": "Votre essai Professionnel comprend un accès complet au plan pendant un mois. Aucune carte de crédit n'est requise.",
  Back: "Retour",
  "Creating workspace...": "Création de l'espace de travail...",
  "Create workspace": "Créer l'espace de travail",
  "No forecast data available": "Aucune donnée de prévision disponible",
  Historical: "Historique",
  Growing: "En hausse",
  Declining: "En baisse",
  Stable: "Stable",
  "Forecast Summary": "Résumé des prévisions",
  "Key forecast indicators.": "Principaux indicateurs de prévision.",
  "Dataset-derived forecast": "Prévision dérivée du jeu de données",
  "Current Value": "Valeur actuelle",
  "Forecast Value": "Valeur prévue",
  "Projected for": "Prévu pour",
  "Projected horizon": "Horizon projeté",
  Change: "Variation",
  Trend: "Tendance",
  "No chartable trend is available for this dataset yet. Use data with a date or period column and at least one numeric metric.": "Aucune tendance exploitable n'est encore disponible pour ce jeu de données. Utilisez une colonne de date ou de période et au moins une métrique numérique.",
  "Automatically generated from uploaded dataset.": "Généré automatiquement à partir du jeu de données téléversé.",
  "Select at least two datasets to compare.": "Sélectionnez au moins deux jeux de données à comparer.",
  "Choose a date column for each dataset.": "Choisissez une colonne de date pour chaque jeu de données.",
  "Wait for the selected dataset columns to finish loading.": "Attendez la fin du chargement des colonnes des jeux de données sélectionnés.",
  "Select at least one metric or column for each dataset.": "Sélectionnez au moins une métrique ou colonne pour chaque jeu de données.",
  "Unable to join the selected datasets.": "Impossible de joindre les jeux de données sélectionnés.",
  "The joined evidence uses a dataset that is no longer available. Reset and recreate the join.": "Les éléments joints utilisent un jeu de données qui n'est plus disponible. Réinitialisez puis recréez la jointure.",
  "Review the joined metrics and agree on the next action.": "Examinez les métriques jointes et convenez de la prochaine action.",
  "Latest shared period:": "Dernière période commune :",
  "Latest evidence:": "Derniers éléments probants :",
  "Select an outcome metric in Decision Details only if this decision needs numeric outcome measurement.": "Sélectionnez une métrique de résultat dans les détails de la décision uniquement si cette décision nécessite une mesure numérique du résultat.",
  "Agree on an action based on the joined evidence and measure the result by the review date.": "Convenez d'une action fondée sur les éléments joints et mesurez le résultat à la date de révision.",
  "Unable to create a decision from the joined evidence.": "Impossible de créer une décision à partir des éléments joints.",
  "Join data for a decision": "Joindre des données pour une décision",
  "Normalize every selected date to a month-year period before joining. Choose the metrics or columns to carry forward; numeric columns use the selected": "Normalisez chaque date sélectionnée en période mois-année avant la jointure. Choisissez les métriques ou colonnes à conserver ; les colonnes numériques utilisent l'agrégation sélectionnée",
  "aggregation.": ".",
  selected: "sélectionnés",
  primary: "principal",
  "Unknown start": "Début inconnu",
  to: "à",
  "unknown end": "fin inconnue",
  "Date column": "Colonne de date",
  "Choose date": "Choisir une date",
  "Metrics or columns to include": "Métriques ou colonnes à inclure",
  "Unselect all metrics or columns": "Désélectionner toutes les métriques ou colonnes",
  "Unselect all": "Tout désélectionner",
  "Reset metrics or columns to the default selection": "Réinitialiser les métriques ou colonnes à la sélection par défaut",
  "Reset to default": "Réinitialiser par défaut",
  "Inspecting dataset columns...": "Inspection des colonnes des jeux de données...",
  "Select one or more additional datasets to continue.": "Sélectionnez un ou plusieurs jeux de données supplémentaires pour continuer.",
  "Inner join on shared month-year periods using": "Jointure interne sur les périodes mois-année communes avec",
  "Dashboard grouping is": "Le regroupement du tableau de bord est",
  "Joining data...": "Jointure des données...",
  "Join selected data": "Joindre les données sélectionnées",
  "Joined evidence ready": "Éléments joints prêts",
  "shared periods from": "périodes communes provenant de",
  "datasets and": "jeux de données et",
  "joined columns, with": "colonnes jointes, avec",
  "period coverage.": "de couverture des périodes.",
  "Create decision from evidence": "Créer une décision à partir des éléments probants",
  "Remove the joined view and return to the original dataset": "Supprimer la vue jointe et revenir au jeu de données original",
  "Reset joined data": "Réinitialiser les données jointes",
  Period: "Période",
  "Anomaly detection": "Détection des anomalies",
  "Statistical outliers in the selected dataset window. This identifies unusual values and does not infer their cause.": "Valeurs aberrantes statistiques dans la fenêtre du jeu de données sélectionné. Cette fonction repère les valeurs inhabituelles sans en déduire la cause.",
  Sensitivity: "Sensibilité",
  "Anomaly detection sensitivity": "Sensibilité de la détection des anomalies",
  High: "Élevée",
  Balanced: "Équilibrée",
  Low: "Faible",
  "Evaluating the selected time series...": "Évaluation de la série temporelle sélectionnée...",
  Retry: "Réessayer",
  "Detected anomalies": "Anomalies détectées",
  "Metrics evaluated": "Métriques évaluées",
  "Minimum periods": "Périodes minimales",
  "Anomaly detection could not be evaluated for this selection.": "La détection des anomalies n'a pas pu être évaluée pour cette sélection.",
  "No numeric metrics are available for this dataset.": "Aucune métrique numérique n'est disponible pour ce jeu de données.",
  detected: "détectées",
  "No anomalies detected.": "Aucune anomalie détectée.",
  value: "valeur",
  Observed: "Observé",
  "vs baseline": "par rapport à la référence",
  score: "score",
  "Creating decision...": "Création de la décision...",
  "Create decision": "Créer une décision",
  "Switch account": "Changer de compte",
  "Acme Inc": "Acme Inc",
  people: "personnes",
  clients: "clients",
  "Direct company workspace": "Espace de travail d'entreprise",
  "Agency client portfolio": "Portefeuille de clients d'agence",
  "Shared client reporting portal": "Portail partagé de rapports clients",
  Business: "Entreprise",
  "For your own business workspace.": "Pour votre propre espace de travail d'entreprise.",
  "Professional trial · 5,000 Decisionate AI credits/month": "Essai Professionnel · 5 000 crédits IA Decisionate/mois",
  "For an agency managing client workspaces.": "Pour une agence qui gère des espaces de travail clients.",
  "Agency trial · Up to 10 client workspaces · 25,000 credits/month": "Essai Agence · Jusqu'à 10 espaces clients · 25 000 crédits/mois",
  Canada: "Canada",
  "United States": "États-Unis",
  "United Kingdom": "Royaume-Uni",
  Australia: "Australie",
  "New Zealand": "Nouvelle-Zélande",
  Other: "Autre",
  "Relationship removed.": "Relation supprimée.",
  "Unable to remove relationship.": "Impossible de supprimer la relation.",
  Refresh: "Actualiser",
  "Define a relationship": "Définir une relation",
  "Decisionate calculates the relationship from aligned data. It does not imply that one metric caused the other.": "Decisionate calcule la relation à partir de données alignées. Cela n'implique pas qu'une métrique ait causé l'autre.",
  "Loading datasets...": "Chargement des jeux de données...",
  "Add at least two datasets before defining a cross-source relationship.": "Ajoutez au moins deux jeux de données avant de définir une relation entre sources.",
  "Relationship name": "Nom de la relation",
  "Marketing spend and revenue": "Dépenses marketing et revenus",
  Aggregation: "Agrégation",
  Timing: "Synchronisation",
  "Automatic (recommended)": "Automatique (recommandé)",
  "Advanced manual": "Manuelle avancée",
  "Decisionate checks a bounded timing window.": "Decisionate vérifie une fenêtre de synchronisation limitée.",
  "Advanced correlation options": "Options avancées de corrélation",
  "Correlation method": "Méthode de corrélation",
  "Pearson (default)": "Pearson (par défaut)",
  "Spearman (rank-based)": "Spearman (fondée sur les rangs)",
  "Left metric leads by": "La métrique de gauche précède de",
  day: "jour",
  week: "semaine",
  month: "mois",
  quarter: "trimestre",
  "Same period": "Même période",
  later: "plus tard",
  "Manual timing is preserved for advanced analysis.": "La synchronisation manuelle est conservée pour l'analyse avancée.",
  "Pearson is the default for measuring linear movement between metrics. Spearman is useful when metrics move consistently together but not in a straight line, or when outliers may distort the result.": "Pearson est la méthode par défaut pour mesurer l'évolution linéaire entre les métriques. Spearman est utile lorsque les métriques évoluent ensemble de façon cohérente sans suivre une ligne droite, ou lorsque des valeurs aberrantes peuvent fausser le résultat.",
  "Loading dataset columns...": "Chargement des colonnes des jeux de données...",
  Calculating: "Calcul en cours",
  "Calculating...": "Calcul en cours...",
  "Preview relationship": "Prévisualiser la relation",
  "Save relationship": "Enregistrer la relation",
  "Saved relationships": "Relations enregistrées",
  "Delete relationship": "Supprimer la relation",
  Dataset: "Jeu de données",
  "Numeric metric": "Métrique numérique",
  Choose: "Choisir",
  "Relationship evidence": "Éléments probants de la relation",
  "Association does not establish causation.": "Une association n'établit pas un lien de causalité.",
  "Shared periods": "Périodes communes",
  Method: "Méthode",
  "Best observed delay": "Meilleur décalage observé",
  "View timing evidence": "Voir les éléments probants de synchronisation",
  Delay: "Décalage",
  Correlation: "Corrélation",
  Periods: "Périodes",
  Credible: "Crédible",
  Limited: "Limitée",
  Saved: "Enregistré",
  canonical: "canonique",
  customer: "client",
  product: "produit",
  "records and created": "enregistrements canoniques et créé",
  "a unified dataset": "un jeu de données unifié",
  "Choose source datasets": "Choisir les jeux de données sources",
  "Entity type": "Type d'entité",
  Customers: "Clients",
  Products: "Produits",
  rows: "lignes",
  "Identity columns by dataset": "Colonnes d'identité par jeu de données",
  "Select one or more columns that identify the same customer or product across sources.": "Sélectionnez une ou plusieurs colonnes qui identifient le même client ou produit entre les sources.",
  "Loading columns...": "Chargement des colonnes...",
  "Loading available columns...": "Chargement des colonnes disponibles...",
  "No columns available.": "Aucune colonne disponible.",
  Suggested: "Suggéré",
  "Select at least one column before previewing or saving.": "Sélectionnez au moins une colonne avant la prévisualisation ou l'enregistrement.",
  "These fields will be carried into the unified dataset. Numeric fields are selected by default.": "Ces champs seront intégrés au jeu de données unifié. Les champs numériques sont sélectionnés par défaut.",
  "No non-identity columns are available.": "Aucune colonne non identitaire n'est disponible.",
  "Select at least one field to include.": "Sélectionnez au moins un champ à inclure.",
  "Preview matches": "Prévisualiser les correspondances",
  "Save matches": "Enregistrer les correspondances",
  "Match preview": "Prévisualisation des correspondances",
  "Source rows": "Lignes sources",
  "Canonical groups": "Groupes canoniques",
  "Rows matched across sources": "Lignes appariées entre les sources",
  "Saved canonical records": "Enregistrements canoniques enregistrés",
  "high confidence": "confiance élevée",
  medium: "moyenne",
  review: "à examiner",
  "Canonical records": "Enregistrements canoniques",
  "Rows needing review": "Lignes à examiner",
  Open: "Ouvrir",
  "unified dataset": "jeu de données unifié",
  "Action needed decisions could not be loaded.": "Les décisions nécessitant une action n'ont pas pu être chargées.",
  "Refreshing...": "Actualisation...",
  "Loading action needed decisions...": "Chargement des décisions nécessitant une action...",
  "Action needed is unavailable": "Les actions requises sont indisponibles",
  "We could not load the follow-up queue. Use Try again above to reload it.": "La file de suivi n'a pas pu être chargée. Utilisez Réessayer ci-dessus pour la recharger.",
  "No action needed": "Aucune action requise",
  "Pending outcomes, learning follow-ups and overdue reviews are clear.": "Les résultats, suivis d'apprentissage et révisions en retard sont à jour.",
  "View decisions": "Voir les décisions",
  "New Decision": "Nouvelle décision",
  "Action needed filters": "Filtres des actions requises",
  "No decisions in this slice": "Aucune décision dans cette sélection",
  "Pick another queue filter to continue reviewing follow-up work.": "Choisissez un autre filtre pour continuer l'examen du suivi.",
  "Show all action-needed decisions": "Afficher toutes les décisions nécessitant une action",
  "No description provided.": "Aucune description fournie.",
  "Action:": "Action :",
  "Metric:": "Métrique :",
  "Analysis:": "Analyse :",
  "Resolve next action": "Résoudre la prochaine action",
  "Checking workspace access...": "Vérification des accès à l'espace de travail...",
  "This client workspace is managed by an agency. Contact the agency to renew the subscription or restore access.": "Cet espace client est géré par une agence. Contactez l'agence pour renouveler l'abonnement ou rétablir l'accès.",
  "Only the business owner can manage billing and subscriptions for this workspace.": "Seul le propriétaire de l'entreprise peut gérer la facturation et les abonnements de cet espace.",
  "Workspace plan": "Plan de l'espace de travail",
  "Start with a 30-day full-access trial without a credit card. Add payment details only when you choose to continue. Additional client capacity is added to the existing subscription and billed on the next renewal invoice.": "Commencez par un essai de 30 jours avec accès complet, sans carte de crédit. Ajoutez vos informations de paiement lorsque vous choisissez de continuer. La capacité client supplémentaire est ajoutée à l'abonnement existant et facturée au prochain renouvellement.",
  "Loading billing status...": "Chargement de l'état de la facturation...",
  Plan: "Plan",
  Renewal: "Renouvellement",
  "Not scheduled": "Non planifié",
  Unlimited: "Illimité",
  "AI credits": "Crédits IA",
  "AI credit pool": "Pool de crédits IA",
  "Agency and client workspaces draw from this shared balance.": "Les espaces d'agence et les espaces clients utilisent ce solde partagé.",
  "Purchase additional credits whenever your workspace needs them.": "Achetez des crédits supplémentaires lorsque votre espace en a besoin.",
  "Your AI credit balance is running low. Add credits to keep analysis available.": "Le solde de vos crédits IA est faible. Ajoutez des crédits pour maintenir l'analyse disponible.",
  "Packs to purchase": "Forfaits à acheter",
  "Opening...": "Ouverture...",
  "Top up AI credits": "Recharger les crédits IA",
  "Each pack adds": "Chaque forfait ajoute",
  "credits. There is no workspace limit on the number of packs purchased.": "crédits. Le nombre de forfaits achetés n'est pas limité par espace.",
  "AI credit top-ups are not configured on this server yet.": "Les recharges de crédits IA ne sont pas encore configurées sur ce serveur.",
  "Payment needs attention": "Le paiement nécessite votre attention",
  "Subscription access is paused": "L'accès à l'abonnement est suspendu",
  "Subscription action required": "Une action est requise pour l'abonnement",
  "Review billing to keep this workspace active.": "Examinez la facturation pour maintenir cet espace actif.",
  "Manage subscription": "Gérer l'abonnement",
  "Billing is not configured on this server yet. Set the Stripe environment values before enabling checkout.": "La facturation n'est pas encore configurée sur ce serveur. Définissez les variables d'environnement Stripe avant d'activer le paiement.",
  "Choose your Decisionate plan": "Choisissez votre plan Decisionate",
  "Agency pricing scales with client workspaces, not employee seats.": "Les tarifs Agence évoluent selon les espaces clients, et non selon les sièges employés.",
  "Billing interval": "Intervalle de facturation",
  "Annual · 2 months free": "Annuel · 2 mois gratuits",
  "Direct business": "Entreprise directe",
  Selected: "Sélectionné",
  year: "an",
  "Up to": "Jusqu'à",
  "client workspaces": "espaces clients",
  "1 workspace with full access": "1 espace de travail avec accès complet",
  "Client portal, agency branding, industry dashboards, decision tracking, and priority support.": "Portail client, image de marque de l'agence, tableaux de bord sectoriels, suivi des décisions et assistance prioritaire.",
  "Unlimited datasets, all dashboards, AI recommendations, decision management, and outcome tracking.": "Jeux de données illimités, tous les tableaux de bord, recommandations IA, gestion des décisions et suivi des résultats.",
  "Stripe price not configured yet": "Le prix Stripe n'est pas encore configuré",
  "Additional client workspaces": "Espaces clients supplémentaires",
  "Extra workspaces": "Espaces supplémentaires",
  "Additional AI credit packs": "Forfaits de crédits IA supplémentaires",
  "Each monthly pack adds": "Chaque forfait mensuel ajoute",
  "credits.": "crédits.",
  Packs: "Forfaits",
  "Add-on price not configured": "Le prix du module complémentaire n'est pas configuré",
  "Available with monthly billing.": "Disponible avec la facturation mensuelle.",
  "Includes a 30-day full-access trial.": "Comprend un essai de 30 jours avec accès complet.",
  "Includes a 30-day full-access trial and agency client portal features.": "Comprend un essai de 30 jours avec accès complet et les fonctions de portail client d'agence.",
  "Continue to annual plan": "Continuer vers le plan annuel",
  "Continue to paid plan": "Continuer vers le plan payant",
  "Start 30-day free trial": "Commencer l'essai gratuit de 30 jours",
  "Agency billing is portfolio-based": "La facturation Agence est fondée sur le portefeuille",
  "Connection access is not available to workspace members.": "L'accès aux connexions n'est pas disponible pour les membres de l'espace.",
  "Data Sources": "Sources de données",
  "Add an external connector, then configure its account details and authorize it before syncing data into a dataset. File uploads are available from Datasets.": "Ajoutez un connecteur externe, configurez ses détails de compte et autorisez-le avant de synchroniser les données dans un jeu de données. Les téléversements de fichiers sont disponibles dans Jeux de données.",
  "This connector is not enabled on the server yet.": "Ce connecteur n'est pas encore activé sur le serveur.",
  "Setup needed": "Configuration requise",
  Planned: "Planifié",
  "Saving...": "Enregistrement...",
  Added: "Ajouté",
  "Add connection": "Ajouter une connexion",
  "Saved data source connections are unavailable. Retry the data services above.": "Les connexions aux sources de données enregistrées sont indisponibles. Réessayez les services de données ci-dessus.",
  "No external data source connections have been added yet. Add one from the available connections above.": "Aucune connexion à une source de données externe n'a encore été ajoutée. Ajoutez-en une parmi les connexions disponibles ci-dessus.",
  Save: "Enregistrer",
  Cancel: "Annuler",
  "Objects selected": "Objets sélectionnés",
  "No objects selected": "Aucun objet sélectionné",
  "OAuth configured": "OAuth configuré",
  "OAuth not configured": "OAuth non configuré",
  Authorization: "Autorisation",
  "OAuth authorization required": "Autorisation OAuth requise",
  "Connection settings required": "Paramètres de connexion requis",
  "Customer ID saved": "ID client enregistré",
  "Customer ID not saved": "ID client non enregistré",
  "Config saved": "Configuration enregistrée",
  "No config saved": "Aucune configuration enregistrée",
  "Last sync:": "Dernière synchronisation :",
  "Authorization requires attention": "L'autorisation nécessite votre attention",
  "Select Reconnect with OAuth to resume scheduled ingestion.": "Sélectionnez Reconnecter avec OAuth pour reprendre l'ingestion planifiée.",
  ready: "prêt",
  "needs setup": "configuration requise",
  "Syncing...": "Synchronisation...",
  "Sync now": "Synchroniser maintenant",
  dataset: "jeu de données",
  Go: "Aller",
  "Go to": "Aller à",
  "Go to dataset": "Aller au jeu de données",
  "Reconnect with OAuth": "Reconnecter avec OAuth",
  "Connect with OAuth": "Connecter avec OAuth",
  "Cancelling...": "Annulation...",
  "Cancel authorization": "Annuler l'autorisation",
  "Hide settings": "Masquer les paramètres",
  "Show settings": "Afficher les paramètres",
  Configure: "Configurer",
  Rename: "Renommer",
  "Removing...": "Suppression...",
  Remove: "Supprimer",
  "What to enter and example values": "Valeurs à saisir et exemples",
  "Enter in this connection": "Saisissez dans cette connexion",
  "Example:": "Exemple :",
  "Use a dedicated read-only database user. The database server must be reachable from the Decisionate API, and the query must be a single read-only SELECT or WITH statement using your database's tables and columns.": "Utilisez un utilisateur de base de données dédié en lecture seule. Le serveur de base de données doit être accessible depuis l'API Decisionate et la requête doit être une seule instruction SELECT ou WITH en lecture seule utilisant les tables et colonnes de votre base.",
  "Dataset Settings": "Paramètres du jeu de données",
  "Configure connection settings": "Configurer les paramètres de connexion",
  "Connection settings": "Paramètres de connexion",
  "Use Connect with OAuth to authorize the provider account, then select the": "Utilisez Connecter avec OAuth pour autoriser le compte du fournisseur, puis sélectionnez les",
  "objects to ingest.": "objets à ingérer.",
  "Save the client store URL first, then use Connect with OAuth to authorize that WooCommerce store.": "Enregistrez d'abord l'URL de la boutique cliente, puis utilisez Connecter avec OAuth pour autoriser cette boutique WooCommerce.",
  "Save the connection fields first, then use Connect with OAuth to authorize the provider account.": "Enregistrez d'abord les champs de connexion, puis utilisez Connecter avec OAuth pour autoriser le compte du fournisseur.",
  "Save the connection settings before selecting objects to ingest.": "Enregistrez les paramètres de connexion avant de sélectionner les objets à ingérer.",
  "Save the resource types before connecting with OAuth.": "Enregistrez les types de ressources avant de vous connecter avec OAuth.",
  "Save the resource types before selecting objects to ingest.": "Enregistrez les types de ressources avant de sélectionner les objets à ingérer.",
  "Connection settings are managed by this provider.": "Les paramètres de connexion sont gérés par ce fournisseur.",
  "Insights setup": "Configuration des analyses",
  "Choose the dataset to analyze for generated patterns, anomalies, and recommendations.": "Choisissez le jeu de données à analyser pour les tendances, anomalies et recommandations générées.",
  "Refreshing insights...": "Actualisation des analyses...",
  "Loading insights...": "Chargement des analyses...",
  Metric: "Métrique",
  "Start date": "Date de début",
  "1 month": "1 mois",
  "1 quarter": "1 trimestre",
  "6 months": "6 mois",
  "1 year": "1 an",
  "2 years": "2 ans",
  "3 years": "3 ans",
  "5 years": "5 ans",
  "All data": "Toutes les données",
  "Group by": "Regrouper par",
  Daily: "Quotidien",
  Weekly: "Hebdomadaire",
  Monthly: "Mensuel",
  Quarterly: "Trimestriel",
  Aggregate: "Agrégat",
  Sum: "Somme",
  Count: "Décompte",
  Average: "Moyenne",
  Minimum: "Minimum",
  Maximum: "Maximum",
  "Reset range": "Réinitialiser la période",
  "Built for mixed customers": "Conçu pour des clients variés",
  "Start simple now. Later, settings lets you brand the workspace, add teammates, and share client access when needed.": "Commencez simplement. Plus tard, les paramètres vous permettront de personnaliser l'espace, d'ajouter des coéquipiers et de partager l'accès client au besoin.",
  "Unable to stop all dashboard sharing.": "Impossible d'arrêter le partage de tous les tableaux de bord.",
  Stopping: "Arrêt en cours",
  "Stopping...": "Arrêt en cours...",
  "Stop all sharing": "Arrêter tous les partages",
  "Stop all sharing for": "Arrêter tous les partages pour",
  "active dashboard share links.": "liens de partage actifs du tableau de bord.",
  "Stop all dashboard sharing.": "Arrêter le partage de tous les tableaux de bord.",
  "Retry dashboard preference": "Réessayer la préférence du tableau de bord",
  "Retry sharing status": "Réessayer le statut du partage",
  "Currently selected": "Sélectionné actuellement",
  "Uses decision records": "Utilise les fiches de décision",
  "Uses dataset metrics": "Utilise les métriques du jeu de données",
  "Open Dashboard": "Ouvrir le tableau de bord",
  "Use Dashboard": "Utiliser le tableau de bord",
  "Loading workspace data access...": "Chargement des accès aux données de l'espace de travail...",
  "Upload and manage datasets used for dashboards, insights, forecasts, and decisions.": "Téléversez et gérez les jeux de données utilisés pour les tableaux de bord, analyses, prévisions et décisions.",
  "Review datasets shared by the workspace team for dashboards, insights, forecasts, and decisions.": "Examinez les jeux de données partagés par l'équipe de l'espace pour les tableaux de bord, analyses, prévisions et décisions.",
  "Retry data services": "Réessayer les services de données",
  "Upload CSV, Excel, JSON or Parquet files directly into the workspace.": "Téléversez directement des fichiers CSV, Excel, JSON ou Parquet dans l'espace de travail.",
  "Saved Datasets": "Jeux de données enregistrés",
  "Upload Data File": "Téléverser un fichier de données",
  "need workspace setup before upload.": "nécessitent une configuration de l'espace avant le téléversement.",
  "Uploading data file...": "Téléversement du fichier de données...",
  "Uploaded File": "Fichier téléversé",
  "Sign in before uploading a dataset.": "Connectez-vous avant de téléverser un jeu de données.",
  "Upload failed": "Échec du téléversement",
  "Sign in before importing a cloud file.": "Connectez-vous avant d'importer un fichier infonuagique.",
  "Paste a signed file URL first.": "Collez d'abord une URL de fichier signée.",
  Imported: "Importé",
  "Cloud file import failed.": "L'importation du fichier infonuagique a échoué.",
  "Import from Google Drive or OneDrive": "Importer depuis Google Drive ou OneDrive",
  "Paste a signed download URL for a CSV, JSON, Excel, or Parquet file.": "Collez une URL de téléchargement signée pour un fichier CSV, JSON, Excel ou Parquet.",
  "Signed file URL": "URL du fichier signé",
  "File name (optional)": "Nom du fichier (facultatif)",
  "Importing...": "Importation...",
  "Import file": "Importer le fichier",
  "Saved Connection Status": "État des connexions enregistrées",
  "Review saved external connections and their dataset sync status.": "Examinez les connexions externes enregistrées et l'état de synchronisation de leurs jeux de données.",
  "Manage connections": "Gérer les connexions",
  "Saved connections are unavailable. Retry the data services above.": "Les connexions enregistrées sont indisponibles. Réessayez les services de données ci-dessus.",
  "No external connections have been added yet. Open Connections to add a provider, or upload a file from Datasets.": "Aucune connexion externe n'a encore été ajoutée. Ouvrez Connexions pour ajouter un fournisseur ou téléversez un fichier depuis Jeux de données.",
  Connection: "Connexion",
  Source: "Source",
  Status: "État",
  Setup: "Configuration",
  "Configuration saved": "Configuration enregistrée",
  "Needs configuration": "Configuration requise",
  Credentials: "Identifiants",
  Ready: "Prêt",
  "Needs setup": "Configuration requise",
  "Configure the GA4 property and use Sync now from Manage connections to create a dataset.": "Configurez la propriété GA4 et utilisez Synchroniser maintenant depuis Gérer les connexions pour créer un jeu de données.",
  "Use Manage connections to finish setup or authorization, then sync the source to create a dataset.": "Utilisez Gérer les connexions pour terminer la configuration ou l'autorisation, puis synchronisez la source pour créer un jeu de données.",
  "Sign in before deleting a dataset.": "Connectez-vous avant de supprimer un jeu de données.",
  "Delete this dataset?": "Supprimer ce jeu de données ?",
  "Failed to delete dataset": "Échec de la suppression du jeu de données",
  "The saved dataset list is unavailable. Retry the data services above.": "La liste des jeux de données enregistrés est indisponible. Réessayez les services de données ci-dessus.",
  "No saved datasets yet. Upload a file above or pull from a configured connection so dashboards, forecasts, reports, alerts, and decisions can use real metrics.": "Aucun jeu de données enregistré. Téléversez un fichier ci-dessus ou importez-le depuis une connexion configurée afin que les tableaux de bord, prévisions, rapports, alertes et décisions utilisent de vraies métriques.",
  "No datasets have been shared with this workspace yet. Ask the workspace team to share one so dashboards, forecasts, reports, alerts, and decisions can use real metrics.": "Aucun jeu de données n'a encore été partagé avec cet espace. Demandez à l'équipe de l'espace d'en partager un afin que les tableaux de bord, prévisions, rapports, alertes et décisions utilisent de vraies métriques.",
  Rows: "Lignes",
  Columns: "Colonnes",
  "source type": "type de source",
  "source types": "types de sources",
  columns: "colonnes",
  "Stored as": "Stocké comme",
  "Original file:": "Fichier original :",
  View: "Voir",
  "Delete dataset": "Supprimer le jeu de données",
  Deleting: "Suppression",
  Delete: "Supprimer",
}

export type DecisionateTranslationKey =
  keyof typeof translations.en

export function getCurrentDecisionateLanguage(): DecisionateLanguage {
  if (typeof document === "undefined") {
    return "en"
  }

  return document.documentElement.lang
    .toLowerCase()
    .startsWith("fr")
    ? "fr"
    : "en"
}

export function applyDecisionateLanguage(
  language: DecisionateLanguage
) {
  if (typeof document === "undefined") {
    return
  }

  document.documentElement.lang =
    languageLocales[language]

  try {
    window.localStorage.setItem(
      decisionateLanguageStorageKey,
      language
    )
  } catch {
    // Storage can be unavailable in strict privacy contexts.
  }

  window.dispatchEvent(
    new CustomEvent<DecisionateLanguageChange>(
      decisionateLanguageChangedEvent,
      {
        detail: { language },
      }
    )
  )
}

export function toggleDecisionateLanguage(
  currentLanguage = getCurrentDecisionateLanguage()
) {
  const nextLanguage =
    currentLanguage === "fr" ? "en" : "fr"

  applyDecisionateLanguage(nextLanguage)

  return nextLanguage
}

export function getDecisionateText(
  language: DecisionateLanguage,
  key: DecisionateTranslationKey
) {
  return translations[language][key]
}

export function getLandingText(
  language: DecisionateLanguage,
  source: string
) {
  return language === "fr"
    ? frenchLandingTranslations[source] ?? source
    : source
}

export function getServerDecisionateLanguage(): DecisionateLanguage {
  return "en"
}
