import type { AIAnalysis } from "@/lib/api"

export function getAIAnalysisSourceLabel(
  analysis: AIAnalysis
) {
  if (analysis.source !== "rules") {
    return `AI analysis (${analysis.model || "configured provider"})`
  }

  if (analysis.fallback_reason === "provider_unavailable") {
    return "deterministic rules fallback (AI provider unavailable)"
  }

  if (analysis.fallback_reason === "unsupported_provider") {
    return "deterministic rules fallback (unsupported AI provider)"
  }

  if (analysis.fallback_reason === "credits_exhausted") {
    return "deterministic rules fallback (AI credits exhausted)"
  }

  return "deterministic rules fallback (AI provider not configured)"
}

export function getAIAnalysisProvenance(
  analysis: AIAnalysis
) {
  if (analysis.source !== "rules") {
    return `Generated by ${analysis.model || "configured AI provider"}.`
  }

  if (analysis.fallback_reason === "provider_unavailable") {
    return "AI provider unavailable; showing deterministic baseline rules."
  }

  if (analysis.fallback_reason === "unsupported_provider") {
    return "AI provider is not supported; showing deterministic baseline rules."
  }

  if (analysis.fallback_reason === "credits_exhausted") {
    return "AI credits are exhausted; showing deterministic baseline rules. Add credits or upgrade the plan to continue with AI analysis."
  }

  return "No AI provider configured; showing deterministic baseline rules."
}

export function getAIAnalysisLearningContext(
  analysis: AIAnalysis
) {
  const learningContext =
    analysis.learning_context

  if (!learningContext) {
    return ""
  }

  const evidenceParts: string[] = []
  const outcomeCount =
    learningContext.recorded_outcome_count || 0
  const lessonCount =
    learningContext.recorded_lesson_count || 0
  const recommendationCount =
    learningContext.recorded_recommendation_count || 0
  const successfulOutcomeCount =
    learningContext.successful_outcome_count || 0
  const partiallySuccessfulOutcomeCount =
    learningContext.partially_successful_outcome_count || 0
  const unsuccessfulOutcomeCount =
    learningContext.unsuccessful_outcome_count || 0
  const historicalSuccessRate =
    learningContext.historical_success_rate
  const scopeCopy = {
    workspace: "workspace decisions",
    dataset: "this dataset's decisions",
    metric: "this metric's decisions",
    decision: "this decision's history",
  }[learningContext.learning_scope || "workspace"] ||
    "workspace decisions"

  if (outcomeCount > 0) {
    const outcomeBreakdown = [
      successfulOutcomeCount > 0
        ? `${successfulOutcomeCount} successful`
        : "",
      partiallySuccessfulOutcomeCount > 0
        ? `${partiallySuccessfulOutcomeCount} partially successful`
        : "",
      unsuccessfulOutcomeCount > 0
        ? `${unsuccessfulOutcomeCount} unsuccessful`
        : "",
    ]
      .filter(Boolean)
      .join(", ")
    const outcomeLabel =
      `${outcomeCount} recorded decision outcome${outcomeCount === 1 ? "" : "s"}`
    evidenceParts.push(
      outcomeBreakdown
        ? `${outcomeLabel} (${outcomeBreakdown})`
        : outcomeLabel
    )

    if (historicalSuccessRate != null) {
      evidenceParts.push(
        `${Math.round(historicalSuccessRate * 100)}% weighted historical success signal`
      )
    }
  }

  if (lessonCount > 0) {
    evidenceParts.push(
      `${lessonCount} recorded decision lesson${lessonCount === 1 ? "" : "s"}`
    )
  }

  if (recommendationCount > 0) {
    evidenceParts.push(
      `${recommendationCount} prior recommendation${recommendationCount === 1 ? "" : "s"} with recorded results`
    )
  }

  return evidenceParts.length > 0
    ? `Informed by ${evidenceParts.join(" and ")} from ${scopeCopy}.`
    : ""
}
