import type { AIAnalysis } from "@/lib/api"

export function getAIAnalysisSourceLabel(
  analysis: AIAnalysis
) {
  if (analysis.source === "openai") {
    return `AI analysis (${analysis.model || "configured provider"})`
  }

  if (analysis.fallback_reason === "provider_unavailable") {
    return "deterministic rules fallback (AI provider unavailable)"
  }

  if (analysis.fallback_reason === "unsupported_provider") {
    return "deterministic rules fallback (unsupported AI provider)"
  }

  return "deterministic rules fallback (AI provider not configured)"
}

export function getAIAnalysisProvenance(
  analysis: AIAnalysis
) {
  if (analysis.source === "openai") {
    return `Generated by ${analysis.model || "configured AI provider"}.`
  }

  if (analysis.fallback_reason === "provider_unavailable") {
    return "AI provider unavailable; showing deterministic baseline rules."
  }

  if (analysis.fallback_reason === "unsupported_provider") {
    return "AI provider is not supported; showing deterministic baseline rules."
  }

  return "No AI provider configured; showing deterministic baseline rules."
}

export function getAIAnalysisLearningContext(
  analysis: AIAnalysis
) {
  const learningContext =
    analysis.learning_context

  if (!learningContext) {
    return ""
  }

  const evidenceParts: string[] = []
  const outcomeCount =
    learningContext.recorded_outcome_count || 0
  const lessonCount =
    learningContext.recorded_lesson_count || 0
  const scopeCopy = {
    workspace: "workspace decisions",
    dataset: "this dataset's decisions",
    metric: "this metric's decisions",
    decision: "this decision's history",
  }[learningContext.learning_scope || "workspace"] ||
    "workspace decisions"

  if (outcomeCount > 0) {
    evidenceParts.push(
      `${outcomeCount} recorded decision outcome${outcomeCount === 1 ? "" : "s"}`
    )
  }

  if (lessonCount > 0) {
    evidenceParts.push(
      `${lessonCount} recorded decision lesson${lessonCount === 1 ? "" : "s"}`
    )
  }

  return evidenceParts.length > 0
    ? `Informed by ${evidenceParts.join(" and ")} from ${scopeCopy}.`
    : ""
}
